/**
 * 后端统一错误码集合。
 *
 * 错误码需要稳定返回给前端，因此所有业务模块新增错误时都应先在这里登记。
 */
export const ERROR_CODES = {
  BACKUP_SNAPSHOT_CONFLICT: "BACKUP_SNAPSHOT_CONFLICT",
  BACKUP_SNAPSHOT_NOT_FOUND: "BACKUP_SNAPSHOT_NOT_FOUND",
  CYCLE_RECORD_NOT_FOUND: "CYCLE_RECORD_NOT_FOUND",
  CYCLE_RECORD_OVERLAPPED: "CYCLE_RECORD_OVERLAPPED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  IDEMPOTENT_REPLAY: "IDEMPOTENT_REPLAY",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_TOKEN: "INVALID_TOKEN",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  PRIVACY_CONFIG_NOT_FOUND: "PRIVACY_CONFIG_NOT_FOUND",
  SESSION_REVOKED: "SESSION_REVOKED",
  UNAUTHORIZED: "UNAUTHORIZED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VAULT_ITEM_NOT_FOUND: "VAULT_ITEM_NOT_FOUND",
  WECHAT_LOGIN_FAILED: "WECHAT_LOGIN_FAILED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
